version: "3"

services:
  flask:
    build: ./core
    environment:
      - FLASK_ENV=production

  caddy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./maze-visualizer/dist:/var/www/static
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
